language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    - tools # to get the new `repository-11.xml`
    - platform-tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - tools
    - build-tools-25.0.1
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-25

  licenses:
   - 'android-sdk-license-.+'

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

sudo: required

install: true

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_failure:
 "cat /home/travis/build/TrebuhD/Clarity/app/build/outputs/lint-results-debug.xml"

script:
  - jdk_switcher use oraclejdk8
  - android list target
  - ./gradlew build connectedCheck --stacktrace