language: android

jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    - tools # to get the new `repository-11.xml`
    - platform-tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - tools
    - build-tools-25.0.1
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-25

  licenses:
   - 'android-sdk-license-.+'
   - '.+'

dependencies:
  override:
    # we are cheating because there is a problem with constraint layout ATM
    # see: https://code.google.com/p/android/issues/detail?id=212128
    - ./gradlew dependencies || true

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

sudo: required

#ConstraintLayout license issue fix
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install: true

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_failure:
 "cat /home/travis/build/TrebuhD/Clarity/app/build/outputs/lint-results-debug.xml"

script:
  - jdk_switcher use oraclejdk8
  - android list target
  - ./gradlew build connectedCheck --stacktrace

notifications:
  email:
    on_failure: change